GET http://localhost:8080/api.book-store/books/
Accept: application/json

###
POST http://localhost:8080/api.book-store/books/
Content-Type: application/json

{
  "name": "Title 44",
  "description": "Description",
  "authors": [
    {
      "authorName": "New Author"
    },
    {
      "authorName": "Test Author 3"
    }
  ]
}

###

PUT http://localhost:8080/api.book-store/books/44
Content-Type: application/json

{
  "name": "Title 44",
  "description": "Description",
  "authors": [
    {
      "authorName": "New Author"
    },
    {
      "authorName": "New Author 2"
    }
  ]
}

###

GET http://localhost:8080/api.book-store/books/26/
Accept: application/json

###

DELETE http://localhost:8080/api.book-store/books/33

###
