GET http://localhost:8080/api.book-store/authors/
Accept: application/json

###

POST http://localhost:8080/api.book-store/authors/
Content-Type: application/json

{
  "authorName": "New Author 4"
}

###

PUT http://localhost:8080/api.book-store/authors/41
Content-Type: application/json

{
  "authorName": "Test Author 2"
}

###

DELETE http://localhost:8080/api.book-store/authors/41

###
