GET http://localhost:8080/api.book-store/books/
Accept: application/json

###
POST http://localhost:8080/api.book-store/books/
Content-Type: application/json

{
  "name": "Title26",
  "description": "Description",
  "authors": [
    {
      "authorName": "New Author"
    }
  ]
}

###

PUT http://localhost:8080/api.book-store/books/25
Content-Type: application/json

{
  "name": "Book 25",
  "description": "Description 25",
  "authors": [
    {
      "authorName": "New Author"
    },
    {
      "authorName": "New Author 2"
    },
    {
      "authorName": "New Author 3"
    }
  ]
}

###

GET http://localhost:8080/api.book-store/books/26/
Accept: application/json

###

DELETE http://localhost:8080/api.book-store/books/26

###

GET http://localhost:8080/api.book-store/authors/
Accept: application/json

###

POST http://localhost:8080/api.book-store/authors/
Content-Type: application/json

{
  "authorName": "New Author 4"
}

###

PUT http://localhost:8080/api.book-store/authors/33
Content-Type: application/json

{
  "authorName": "Test Author 1"
}

###

DELETE http://localhost:8080/api.book-store/authors/34

###

POST http://localhost:8080/api.book-store/test/
